name: Publish release

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - main

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20
      - name: checkout
        uses: actions/checkout@v4

      - name: release
        run: make semantic-release-ci